stages:
- build
- test
- deploy

#before_script:
# - apt-get install python

run-tests:
 type: test
 script:
  - pytest
 only:
  - master

create-docs:
 type: deploy
 script:
  - cd docs/ && make html && cd ..
 only:
  - master

create-package:
 type: deploy
 script:
  - python setup.py sdist
  - pip install dist/*
 only:
  - master