image: python:3.6

stages:
- build
- test
- deploy
- trig

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
###variables:
###    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
###cache:
###  paths:
###    - .cache/
###    - venv/

###before_script:
###  - apt update -y && apt install -y libhdf5-serial-dev ffmpeg
###    # Configure pip caching
###  - python -V               # Print out python version for debugging
###  - pip install virtualenv
###  - virtualenv venv
###  - source venv/bin/activate
###  - pip install --upgrade pip
###  - pip install -r requirements.txt

#run-tests:
# type: test
# script:
#  - pytest

#create-docs:
# type: deploy
# script:
#  - cd docs/ && make html && cd ..
# only:
#  - master

###create-package:
### type: deploy
### script:
###  - python setup.py sdist
###  - pip install dist/sound_classification-0.0.1.tar.gz
#### only:
####  - master
### artifacts:
###  paths:
###   - dist/sound_classification-0.0.1.tar.gz

create-package:
 type: test
 script:
  - cp requirements.txt dummy.txt
  - ls -lhtr
 artifacts:
  paths:
   - dummy.txt

###############################
##  Trig dependant projects   #
###############################

trigger:
  type: trig
  script:
    - curl -X POST -F token=TOKEN -F ref=REF_NAME https://data.meridian.cs.dal.ca/gitlab/api/v4/projects/10/trigger/pipeline


.trig base: &trig
  type: trig
  script:
    - JOB_NAME=( $CI_BUILD_NAME )
    - export TOKEN="${JOB_NAME[1]}_TOKEN"
    - export TOKEN=${!TOKEN}
    - export ID=${JOB_NAME[2]}
    - curl --request POST --form token=`echo $TOKEN` --form ref=master https://data.meridian.cs.dal.ca/api/v4/projects/$ID/trigger/pipeline
    #  only:
#    - master
  dependencies: []
    
#trig HUMPBACK_CLASS 10: # project TOKEN and ID
#  <<: *trig
