image: python:3

stages:
- build
- test
- deploy

before_script:
 - apt update
 - apt install libhdf5-serial-dev
 - pip install --upgrade pip
 - pip install -r requirements.txt

run-tests:
 type: test
 script:
  - pytest

create-docs:
 type: deploy
 script:
  - cd docs/ && make html && cd ..
 only:
  - master

create-package:
 type: deploy
 script:
  - python setup.py sdist
  - pip install dist/*
 only:
  - master
