image: python:3-alpine
stages:
- build
- test
- deploy

before_script:
 - pip install pytest

run-tests:
 type: test
 script:
  - pytest

create-docs:
 type: deploy
 script:
  - cd docs/ && make html && cd ..
 only:
  - master

create-package:
 type: deploy
 script:
  - python setup.py sdist
  - pip install dist/*
 only:
  - master