image: meridiancfi/ketos:v2.6.1

stages:
- build
- test
- deploy
- trig

#before_script:
#  - pip install --upgrade tensorflow

after_script:
  - rm -rf ketos/tests/assets/tmp/*

run-tests:
 stage: test
 script:
  - pytest --doctest-modules --ignore=docs

create-docs:
 stage: deploy
 before_script: # overwrites global before_script
  - pip install --upgrade pip
  - pip install sphinx
  - pip install sphinx_rtd_theme
 script:
  - cd docs/ && make html && cd ..
 only:
  - master

create-package:
 stage: deploy
 script:
  - python setup.py sdist
  - pip install dist/ketos-*.tar.gz
 only:
  - master
 artifacts:
  paths:
   - dist/ketos-*.tar.gz


#  Trig dependant projects

# This triggers CI pipeline for master branch of humbpack_class project.
# For guidelines on how to set this up, see here: https://data.meridian.cs.dal.ca/gitlab/data_analytics_dal/projects/humpback_class/settings/ci_cd
### trigger-humpback:
###   before_script: []
###   type: trig
###   script:
###     - "curl -X POST -F token=d1205bf47de18df6e2be7eef55bc8e -F ref=master https://gitlab.meridian.cs.dal.ca/api/v4/projects/10/trigger/pipeline"
###   only:
###   - master
  
# This triggers CI pipeline for master branch of cod_class_amalis project.
### trigger-cod:
###   before_script: []
###   type: trig
###   script:
###     - "curl -X POST -F token=d2b2ee118fff4bef2cb9341eae715f -F ref=master https://gitlab.meridian.cs.dal.ca/api/v4/projects/4/trigger/pipeline"
###   only:
###   - master
