name: ketos_env
dependencies:
  - make
  - pip
  - pytest
  - numpy
  - scipy
  - matplotlib
  - setuptools
  - h5py
  - pandas
  - keras
  - tensorflow
  - pytables
  - tqdm
  - scikit-image
  - scikit-learn
#  - datetime-glob
#  - Pint
#  - librosa
